onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
# Only allow packages that are at least one day old
minimumReleaseAge: 1440
# Except official astro packages and my own ones
minimumReleaseAgeExclude:
  - "@astrojs/*"
  - "astro"
  - "astro-loader-pocketbase"
  - "astro-integration-pocketbase"
