name: 🆙 Update dependencies
# Run this every saturday
on:
  schedule:
    - cron: "0 4 * * 6"
permissions:
  contents: read
jobs:
  update:
    # Use the latest version of Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # Checkout repository
      - name: 📥 Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: "master"

      # Install pnpm
      - name: 📦 Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      # Setup Node
      - name: 📦 Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      # Update dependencies
      - name: 🆙 Update dependencies
        run: |
          pnpm up
          pnpm dedupe

      - name: 🆙 Update GitHub Actions
        run: |
          pnpm dlx actions-up -y --min-age 7

      # Restore cache
      - name: 📦 Restore cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: astro-cache
          path: |
            .astro

      # Check Astro
      - name: 🧪 Check Astro
        run: pnpm run prebuild
        env:
          MATOMO_URL: ${{ vars.MATOMO_URL }}
          MATOMO_SITE_ID: ${{ vars.MATOMO_SITE_ID }}

      # Create pull request
      - name: 🚀 Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "build(deps): update dependencies"
          sign-commits: true
          branch: "build/update-dependencies"
          delete-branch: true
          base: "master"
          title: "Update dependencies"
          body: "This PR updates dependencies."
          labels: "priority/medium,status/testing,team/internal,type/maintenance"
          reviewers: "pawcoding"
